In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
try:
    heart_data = pd.read_csv("F:/projectfinal/Datasets/heart_disease.csv")
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("Error: CSV file not found. Please check the file path.")
    exit()

Dataset loaded successfully.

In [3]:
heart_data = heart_data.drop_duplicates()
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,53,0,3,132,233,0,0.0,154,1.0,0.9,2.0,0.0,2.0,1
1,47,0,3,138,211,0,0.0,125,1.0,0.5,2.0,1.0,2.0,0
2,42,1,3,147,288,0,2.0,135,1.0,2.2,0.0,2.0,3.0,1
3,30,1,1,143,213,0,0.0,140,0.0,1.0,1.0,0.0,1.0,0
4,75,0,1,130,217,0,1.0,131,0.0,1.1,2.0,1.0,2.0,1

In [4]:
heart_data.shape

(2400, 14)

In [5]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2400 entries, 0 to 2399
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       2400 non-null   int64
 1   sex       2400 non-null   int64
 2   cp        2400 non-null   int64
 3   trestbps  2400 non-null   int64
 4   chol      2400 non-null   int64
 5   fbs       2400 non-null   int64
 6   restecg   2400 non-null   float64
 7   thalach   2400 non-null   int64
 8   exang     2400 non-null   float64
 9   oldpeak   2400 non-null   float64
 10  slope     2400 non-null   float64
 11  ca        2400 non-null   float64
 12  thal      2400 non-null   float64
 13  target    2400 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 262.6 KB

In [6]:
# checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
# statistical measures about the data
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000,2400.000000
mean,54.427917,0.602083,1.655417,135.215417,229.580833,0.217917,0.563750,139.930833,0.501667,1.347625,1.335000,0.693750,1.744167,0.500000
std,14.408029,0.489570,1.110792,18.712271,45.750690,0.412916,0.666674,24.285011,0.500101,1.199348,0.748114,0.928432,0.812809,0.500104
min,30.000000,0.000000,0.000000,90.000000,120.000000,0.000000,0.000000,70.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,42.000000,0.000000,1.000000,121.000000,193.000000,0.000000,0.000000,125.000000,0.000000,0.300000,1.000000,0.000000,1.000000,0.000000
50%,54.000000,1.000000,1.000000,135.000000,230.000000,0.000000,0.000000,140.000000,1.000000,1.000000,2.000000,0.000000,2.000000,0.500000
75%,66.000000,1.000000,3.000000,147.000000,255.000000,0.000000,1.000000,155.000000,1.000000,2.300000,2.000000,1.000000,2.000000,1.000000
max,79.000000,1.000000,3.000000,191.000000,376.000000,1.000000,2.000000,200.000000,1.000000,5.500000,2.000000,3.000000,3.000000,1.000000

In [8]:
heart_data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,53,0,3,132,233,0,0.0,154,1.0,0.9,2.0,0.0,2.0,1
1,47,0,3,138,211,0,0.0,125,1.0,0.5,2.0,1.0,2.0,0
2,42,1,3,147,288,0,2.0,135,1.0,2.2,0.0,2.0,3.0,1
3,30,1,1,143,213,0,0.0,140,0.0,1.0,1.0,0.0,1.0,0
4,75,0,1,130,217,0,1.0,131,0.0,1.1,2.0,1.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,41,0,1,137,231,0,1.0,141,1.0,1.0,1.0,0.0,2.0,0
2396,47,1,3,149,252,0,2.0,99,1.0,3.6,1.0,1.0,3.0,1
2397,67,0,0,155,273,1,2.0,122,1.0,1.9,1.0,1.0,3.0,1
2398,38,1,3,162,288,0,1.0,128,1.0,3.6,1.0,1.0,2.0,1
2399,73,1,3,150,294,1,1.0,135,1.0,2.2,1.0,2.0,2.0,1

In [9]:
heart_data['target'].value_counts()

target
1    1200
0    1200
Name: count, dtype: int64

1 --> Defective Heart

0 --> Healthy Heart

Splitting the Features and Target

In [10]:
# --- 2. Data Preprocessing ---
X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=42)

In [12]:
scaler = StandardScaler()

In [13]:
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

In [14]:
cols_to_scale = ['trestbps', 'chol', 'thalach', 'oldpeak']

In [15]:
# Apply the scaler exclusively to those columns. 
# 'age', 'sex', 'cp', etc., remain in their raw, human-readable format!
X_train_scaled[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])
X_test_scaled[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

Model Training

In [16]:

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, Y_train)

RandomForestClassifier(random_state=42)

In [17]:
y_pred = model.predict(X_test_scaled)

In [18]:
# Accuracy Score

print(f"Accuracy of Data:     {accuracy_score(Y_test, y_pred):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_pred))

Accuracy of Data:     0.8396

Confusion Matrix:
[[207  33]
 [ 44 196]]

In [19]:
# Classification Report - Gives Precision/Recall details
print("\nClassification Report:")
print(classification_report(Y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       240
           1       0.86      0.82      0.84       240

    accuracy                           0.84       480
   macro avg       0.84      0.84      0.84       480
weighted avg       0.84      0.84      0.84       480

Predictive System

In [20]:
input_data = (57, 0, 1, 130, 236, 0, 0, 174, 0, 0.0, 1, 1, 2)


# Convert the input tuple directly into a DataFrame
# We use 'X.columns' to ensure the column names match exactly what the model expects
input_df = pd.DataFrame([input_data], columns=X.columns)

print("Input Data Processed:")
print(input_df)



# Make prediction
prediction = model.predict(input_df)

print(f"\nModel Prediction: {prediction[0]}")

if (prediction[0] == 0):
  print('The person does not have a Heart Disease ')
else:
  print('The person has Heart Disease ')

Input Data Processed:
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   57    0   1       130   236    0        0      174      0      0.0      1

   ca  thal
0   1     2

Model Prediction: 1
The person has Heart Disease

Saving the trained model

In [21]:
import pickle

In [22]:
filename = 'heart_disease.sav'
with open(filename, 'wb') as file:
    pickle.dump(model, file)

In [23]:
# loading the saved model
loaded_model = pickle.load(open('heart_disease.sav', 'rb'))

In [24]:
pickle.dump(scaler, open('heart_scaler.sav', 'wb'))