In [266]:
import pandas as pd
import numpy as np
import pickle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC

Data Collection & Analysis

In [267]:
parkinsons_data = pd.read_csv("F:\projectfinal\Datasets\parkinson_data.csv")

In [268]:
parkinsons_data.drop(columns=['name'], inplace=True)

In [269]:
parkinsons_data.head()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [270]:
parkinsons_data.tail()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
341,152.349648,177.167979,130.674813,0.004955,0.000050,0.002230,0.002725,0.006690,0.032724,0.310875,...,0.039268,0.022299,18.264976,0,0.713365,0.714813,-5.305242,0.247075,1.777321,0.188877
342,124.829132,146.162793,104.484936,0.009939,0.000099,0.004473,0.005466,0.013418,0.055925,0.531285,...,0.067110,0.044725,12.349805,1,0.494755,0.789838,-2.850015,0.261058,2.256392,0.332651
343,201.270807,227.388798,190.703673,0.003073,0.000031,0.001383,0.001690,0.004148,0.013584,0.129045,...,0.016300,0.013827,25.823818,0,0.465590,0.672820,-6.272089,0.303604,2.000196,0.166401
344,153.215641,171.773611,133.104955,0.005395,0.000054,0.002428,0.002967,0.007283,0.038619,0.366876,...,0.046342,0.024276,20.744016,0,0.446089,0.616831,-6.403755,0.272910,2.932272,0.147755
345,173.117664,190.078180,151.047506,0.002279,0.000023,0.001026,0.001253,0.003077,0.012180,0.115713,...,0.014616,0.010255,22.939077,0,0.369541,0.758169,-7.699653,0.218674,2.144707,0.103359

In [271]:
parkinsons_data.shape

(346, 23)

In [272]:
parkinsons_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MDVP:Fo(Hz)       346 non-null    float64
 1   MDVP:Fhi(Hz)      346 non-null    float64
 2   MDVP:Flo(Hz)      346 non-null    float64
 3   MDVP:Jitter(%)    346 non-null    float64
 4   MDVP:Jitter(Abs)  346 non-null    float64
 5   MDVP:RAP          346 non-null    float64
 6   MDVP:PPQ          346 non-null    float64
 7   Jitter:DDP        346 non-null    float64
 8   MDVP:Shimmer      346 non-null    float64
 9   MDVP:Shimmer(dB)  346 non-null    float64
 10  Shimmer:APQ3      346 non-null    float64
 11  Shimmer:APQ5      346 non-null    float64
 12  MDVP:APQ          346 non-null    float64
 13  Shimmer:DDA       346 non-null    float64
 14  NHR               346 non-null    float64
 15  HNR               346 non-null    float64
 16  status            346 non-null    int64
 17  RPDE              346 non-null    float64
 18  DFA               346 non-null    float64
 19  spread1           346 non-null    float64
 20  spread2           346 non-null    float64
 21  D2                346 non-null    float64
 22  PPE               346 non-null    float64
dtypes: float64(22), int64(1)
memory usage: 62.3 KB

In [273]:
parkinsons_data.isnull().sum()

MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [274]:
parkinsons_data.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,...,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000,346.000000
mean,154.668051,189.246505,124.669770,0.005539,0.000043,0.002820,0.003057,0.008462,0.029015,0.274057,...,0.042670,0.022277,21.774239,0.531792,0.499522,0.710664,-5.695151,0.235445,2.360894,0.198265
std,36.182576,71.920032,39.036010,0.003973,0.000030,0.002385,0.002251,0.007154,0.016652,0.168804,...,0.025621,0.031100,4.333961,0.499711,0.096007,0.051606,1.069799,0.072781,0.339656,0.082400
min,77.878537,82.534978,57.591790,0.001166,0.000007,0.000525,0.000641,0.001574,0.006890,0.065458,...,0.008268,0.000650,8.441000,0.000000,0.256570,0.570582,-7.964984,0.006274,1.423287,0.044539
25%,123.757759,148.694000,94.249750,0.003322,0.000027,0.001593,0.001820,0.004770,0.016802,0.154000,...,0.024307,0.008584,19.373000,0.000000,0.434400,0.676445,-6.437328,0.192938,2.130738,0.141549
50%,150.209675,177.229490,116.373318,0.004797,0.000040,0.002305,0.002615,0.006911,0.025005,0.229962,...,0.038435,0.015564,22.176987,1.000000,0.496186,0.707670,-5.660473,0.232515,2.348351,0.182780
75%,179.887669,210.504083,151.006090,0.006088,0.000050,0.003210,0.003320,0.009635,0.034533,0.328164,...,0.049093,0.021826,24.938054,1.000000,0.570495,0.741235,-5.186230,0.276844,2.533002,0.240215
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.782433,0.876453,-2.434031,0.450493,3.671155,0.527367

In [275]:
parkinsons_data['status'].value_counts()

status
1    184
0    162
Name: count, dtype: int64

1  --> Parkinson's Positive

0 --> Healthy

In [276]:
# exclude non-numeric columns when computing group means
parkinsons_data.groupby('status').mean(numeric_only=True)

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
status,,,,,,,,,,,,,,,,,,,,,
0,170.068199,199.539410,145.563306,0.003957,0.000032,0.001924,0.002148,0.005774,0.021174,0.196444,...,0.015551,0.030710,0.014178,23.747523,0.487064,0.703050,-6.266498,0.218602,2.289427,0.148413
1,141.109225,180.184273,106.274375,0.006933,0.000054,0.003609,0.003858,0.010828,0.035919,0.342390,...,0.028371,0.053199,0.029408,20.036891,0.510490,0.717368,-5.192118,0.250275,2.423815,0.242156

Data Pre-Processing

In [277]:
print(parkinsons_data.columns)

Index(['MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)',
       'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP',
       'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5',
       'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA',
       'spread1', 'spread2', 'D2', 'PPE'],
      dtype='object')

In [278]:
X = parkinsons_data.drop(columns=[ 'status'], axis=1)
Y = parkinsons_data['status']

In [279]:
# samples with stratify=Y is the standard practice for high accuracy.
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2, stratify=Y)
print("X_train shape: ", X_train.shape)
print("Y_train shape: ", Y_train.shape)
print("X_test shape: ", X_test.shape)
print("Y_test shape: ", Y_test.shape)

X_train shape:  (276, 22)
Y_train shape:  (276,)
X_test shape:  (70, 22)
Y_test shape:  (70,)

In [280]:
scaler = MinMaxScaler()

In [281]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Model Training

In [282]:
# Setup the SVM with poly kernel
poly_svm = SVC(kernel='poly', probability=True, class_weight='balanced', random_state=2)

In [283]:
# 5. Hyperparameter Tuning for the SVM
param_grid_poly = {
    'C': [0.1, 1, 10, 100],        # Regularization (how strict the boundary is)
    'degree': [2, 1],              # How many times the curve can bend
    'gamma': ['scale', 'auto'],    # Curve influence
    'coef0': [0.0, 1.0]            # Independent term that helps shift the curve
}

In [284]:
print("\nTuning SVM parameters...")
grid = GridSearchCV(poly_svm, param_grid_poly, cv=5, scoring='accuracy', n_jobs=-1)
grid.fit(X_train_scaled, Y_train)

Tuning SVM parameters...

GridSearchCV(cv=5,
             estimator=SVC(class_weight='balanced', kernel='poly',
                           probability=True, random_state=2),
             n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'coef0': [0.0, 1.0],
                         'degree': [2, 1], 'gamma': ['scale', 'auto']},
             scoring='accuracy')

In [285]:
# Lock in the best model
best_svm_model = grid.best_estimator_
print("Best Parameters:", grid.best_params_)

Best Parameters: {'C': 10, 'coef0': 0.0, 'degree': 2, 'gamma': 'scale'}

In [286]:
X_test_prediction = best_svm_model.predict(X_test_scaled)
print("\nFinal Accuracy:", accuracy_score(Y_test, X_test_prediction))

Final Accuracy: 0.7857142857142857

In [287]:
print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, X_test_prediction))

Confusion Matrix:
[[28  5]
 [10 27]]

In [288]:
print("\nClassification Report:")
print(classification_report(Y_test, X_test_prediction))

Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.85      0.79        33
           1       0.84      0.73      0.78        37

    accuracy                           0.79        70
   macro avg       0.79      0.79      0.79        70
weighted avg       0.79      0.79      0.79        70

In [289]:
def predict_parkinsons(input_data):
    # 1. Change input data to a numpy array
    input_data_as_numpy_array = np.asarray(input_data)

    # 2. Reshape the numpy array as we are predicting for one instance
    input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

    # 3. Create a DataFrame with the specific column names
    # This tells the scaler exactly which feature corresponds to which number
    input_df = pd.DataFrame(input_data_reshaped, columns=X.columns)

    # 4. STANDARDIZE using the DataFrame 
    std_data = scaler.transform(input_df)

    # 5. Make prediction
    prediction = best_svm_model.predict(std_data)

    if (prediction[0] == 0):
      print("Result: The Person is HEALTHY")
    else:
      print("Result: The Person has PARKINSON'S")


input_data = (116.676, 137.871, 111.366, 0.00997, 0.00009, 0.00502, 0.00698, 0.01505, 0.05492, 0.517, 0.02924, 0.04005, 0.03772, 0.08771, 0.01353, 20.644, 0.434969, 0.819235, -4.117501, 0.334147, 2.405554, 0.368975)
predict_parkinsons(input_data)

Result: The Person has PARKINSON'S

Saving the trained model

In [290]:
import pickle

In [291]:
filename = 'parkinsons_model.sav'
pickle.dump(best_svm_model, open(filename, 'wb'))

In [292]:
# loading the saved model
loaded_model = pickle.load(open('parkinsons_model.sav', 'rb'))

In [293]:
# Save the scaler
pickle.dump(scaler, open('parkinsons_scaler.sav', 'wb'))

In [294]:
# Save a small background dataset for SHAP to use in the app
background_data = X_train_scaled[100:300:5] 
pickle.dump(background_data, open('parkinsons_bg.sav', 'wb'))